name: Publicar en GitHub Packages (Manual)

# Cambiamos el disparador a "workflow_dispatch"
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para escribir en GitHub Packages

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4 # Usamos una versión más reciente

    - name: Configurar Node.js
      uses: actions/setup-node@v4 # Usamos una versión más reciente
      with:
        node-version: '22' # Puedes usar una versión LTS más reciente como la 20
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@erjosara8916' # Asegúrate que tu usuario esté aquí

    - name: Instalar dependencias y compilar
      run: |
        npm ci # 'ci' es más rápido y seguro para workflows
        npm run build

    - name: Publicar el paquete
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}